name: muhaseb_pro
description: "MuhasebPro"
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # State Management & DI
  flutter_riverpod: ^2.5.1

  # Routing
  go_router: ^14.1.0

  # Database
  drift: ^2.22.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.3
  path: ^1.9.0

  equatable: ^2.0.5
  intl: ^0.20.2
  iconsax: ^0.0.8
  crypto: ^3.0.3
  dartz: ^0.10.1

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4

  # Code Generators
  build_runner: ^2.4.9
  drift_dev: ^2.22.0


# For information on the generic Dart part of a this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets: []
  generate: true
